module.exports = {
  PORT: process.env.PORT || 3000,
  TICK_MS: 1000 / 30,
  WORLD_W: 1600,
  WORLD_H: 900,
  TOWER_X_LEFT: 120,
  TOWER_X_RIGHT: 1600 - 120,
  TOWER_Y: 900 / 2,
  GROUND_Y: 900 - 60,
  CARD_Y: 90,
  CARD_W: 90,
  CARD_H: 44,
  UPGRADE_TYPES: [
    'arrowLevel',
    'unitLevel',
    'multiShotLevel',
    'spawnLevel',
    'unitHpLevel',
    'resourceLevel',
    'bountyLevel',
    'explosiveLevel',
    'powerLevel',
    'superMinionLevel',
  ],
  SHOT_POWER_TYPES: ['multiShot', 'ultraShot', 'pierceShot', 'heavyShot'],
};
